DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS films;


CREATE TABLE films(
id SERIAL8 PRIMARY KEY,
title VARCHAR(255),
price NUMERIC
);

CREATE TABLE customers(
id SERIAL8 PRIMARY KEY,
name VARCHAR(255),
funds NUMERIC
);

CREATE TABLE tickets(
id SERIAL8 PRIMARY KEY,
customer_id INT8 REFERENCES customers(id),
film_id INT8 REFERENCES films(id)
);
